# Site settings
title: Nicolas Battaglia
description: A developer website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nicolas Battaglia
user_description: Atypical software engineer. Love for guitar, then backend techs. Always curious.
user_title: Software Engineer
email: nicobatt@hotmail.com
github_username:  https://github.com/zk182
linkedin_username:  https://www.linkedin.com/in/nicobattaglia
medium_username:  https://medium.com/@nicolasbattaglia_22555

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
